apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podinfo

resources:
- ../base
- namespace.yaml
- ingress.yaml

images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.3.0

configMapGenerator:
  - name: podinfo-config
    literals:
    - PODINFO_UI_COLOR=#34577c #5c1694

replacements:
- source:
    fieldPath: metadata.annotations.preview/domain
    kind: Ingress
    name: podinfo
  targets:
  - fieldPaths:
    - spec.rules.0.host
    options:
      create: true
    select:
      kind: Ingress
      name: podinfo

